version: "3"
services:
  htmx-root:
    build:
      context: .
      dockerfile: ./htmx-root/Dockerfile
    ports:
      - 8000:8000

  object-service:
    build:
      context: .
      dockerfile: ./object-service/Dockerfile
    ports:
      - 8001:8001
    environment:
      - DATABASE_URL=${DATABASE_URL}

  lightcurve-service:
    build:
      context: .
      dockerfile: ./lightcurve-service/Dockerfile
    ports:
      - 8002:8002
    environment:
      - DATABASE_URL=${DATABASE_URL}

  aladin-service:
    build:
      context: .
      dockerfile: ./aladin-service/Dockerfile
    ports:
      - 8003:8003
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - OBJECT_SERVICE_URL=http://object-service:8001/object
