version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  initdb:
    build:
      context: .
      dockerfile: ./dbinit/Dockerfile
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=user=postgres password=postgres host=postgres port=5432 dbname=postgres

  lightcurve-service:
    build:
      context: ./lightcurve-service
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=user=postgres password=postgres host=postgres port=5432 dbname=postgres

  htmx-root:
    build:
      context: ./htmx-root
    ports:
      - 8001:8000
